### ISSUE TITLE
Plugin throws TypeError

### ISSUE THREAD

**Issue by dreweslu** [Sunoo/homebridge-rpi-rf-switch#1]
The plugin always throws this error: (vanilla installation, only added provided sample-config)

[2/25/2020, 21:01:21] TypeError: Cannot read property 'forEach' of undefined
   at rfSwitchPlatform.didFinishLaunching (/usr/lib/node_modules/homebridge-rpi-rf-switch/index.js:45:25)
    at API.emit (events.js:311:20)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
[2/25/2020, 21:01:22] Got SIGTERM, shutting down Homebridge...

**Comment by antagosteenl** [comment]
I Have the same error. the python installation (send and receive works) works.

**Comment by ditistijn** [comment]
same for me. anyone solved this?

**Comment by Lukjam** [comment]
The example config is wrong. After "name": "RF Switch", comes "devices":, not "switches":

**Comment by ditistijn** [comment]
Yes! That was it! Great, thanks!
