### ISSUE TITLE
cannot install plugin on hoobs

### ISSUE THREAD

**Issue by danielgoedecke** [Sunoo/homebridge-rpi-rf-switch#126]
try to install the plugin and get errors, 
i did the preinstallation like in the installation manual

1.  Install pip using sudo apt install python3-dev python3-pip.
2.  Install rpi-rf using sudo pip3 install rpi-rf.

--------
hoobs@hoobs:~ $ sudo npm install -g homebridge-rpi-rf-switch --unsafe-perm

> node-calls-python@1.5.2 install /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
> node-gyp rebuild

gyp: Call to 'python3-config --ldflags --embed' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-calls-python@1.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-14T14_38_35_873Z-debug.log

**Comment by Sunoo** [comment]
What happens if you run `python3-config --ldflags --embed` from a terminal?

**Comment by danielgoedecke** [comment]
hoobs@hoobs:~ $ python3-config --ldflags --embed
Usage: /usr/bin/python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir

**Comment by danielgoedecke** [comment]
this happens:

hoobs@hoobs:~ $ python3-config --ldflags --embed
Usage: /usr/bin/python3-config --prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--extension-suffix|--help|--abiflags|--configdir

**Comment by Dmulvihill** [comment]
I think I have a similar issue. I get this when attempting to install the plugin from Homebridge UI:

`USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-rpi-rf-switch@latest

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.0
npm ERR! gyp info using node@14.16.1 | linux | arm
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/homebridge/.cache/node-gyp/14.16.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/homebridge/.cache/node-gyp/14.16.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/homebridge/.cache/node-gyp/14.16.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Call to 'python3-config --ldflags --embed' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 5.10.63-v7l+
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
npm ERR! gyp ERR! node -v v14.16.1
npm ERR! gyp ERR! node-gyp -v v8.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2021-11-24T17_56_35_722Z-debug.log

Command failed. Please review log for details.`

**Comment by Dmulvihill** [comment]
I did a reinstall of Raspbian and all is okay now.

**Comment by vhmgmg** [comment]
Bonsoir,
Je suis nouveau sur ce forum et j’ai même problème d’erreur d’installation !
Dmulvihill, pourrais-tu me donner la procédure à suivre pour réinstaller Raspbian afin de pouvoir installer ce plugin.
Merci d’avance.

**Comment by Spikey85** [comment]
Hello, I have the same problem when I want wo install the homebridge-rpi-rf-switch in Hoobs. Can you help me? I really need your super plugin. I reinstall Hoobs but nothing changed;-) 
Thank you very much and have a great day.

> node-calls-python@1.5.2 install /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
> node-gyp rebuild

gyp: Call to 'python3-config --ldflags --embed' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
gyp ERR! node -v v14.17.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-calls-python@1.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-07T09_53_55_762Z-debug.log

**Comment by Sunoo** [comment]
@Spikey85 Can you share /root/.npm/_logs/2022-01-07T09_53_55_762Z-debug.log

**Comment by Spikey85** [comment]
[Gesicherte Terminal-Ausgabe.txt](https://github.com/Sunoo/homebridge-rpi-rf-switch/files/7829258/Gesicherte.Terminal-Ausgabe.txt)

**Comment by Spikey85** [comment]
Can you Open it and is it the Right?

**Comment by Sunoo** [comment]
I can open it, I haven’t had a chance to look close yet. I’m just finishing up my day job.

**Comment by Spikey85** [comment]
Hello @Sunoo did you find the Problem? I miss my RF Switches so much in my Smart Home 😢 thanks.

**Comment by Spikey85** [comment]
Hey @Sunoo did you find the problem? I hope so much that you can help me. I´m aleady not able to install your Plugin in Hoobs.

**Comment by Spikey85** [comment]
I see now others errors, can this help you? 

npm ERR! code 1
npm ERR! path /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.2 | linux | arm
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/16.13.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.13.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Call to 'python3-config --ldflags --embed' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.10.17-v7l+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-31T08_43_39_380Z-debug.log

And here is the log:

[2022-01-31T08_43_39_380Z-debug.log](https://github.com/Sunoo/homebridge-rpi-rf-switch/files/7971345/2022-01-31T08_43_39_380Z-debug.log)
