### ISSUE TITLE
plugin doesn't start on hoobs

### ISSUE THREAD

**Issue by antagosteenl** [Sunoo/homebridge-rpi-rf-switch#2]
I tryed to use the plugin on hoobs nut it wont strat.

[Homebridge] [3/7/2020, 5:51:43 AM] TypeError: Cannot read property 'forEach' of undefined
    at rfSwitchPlatform.didFinishLaunching (/home/hoobs/.hoobs/node_modules/homebridge-rpi-rf-switch/index.js:45:25)
    at API.emit (events.js:203:15)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:91:15)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

the config has nor devices set. Even when i set one, I get the same error message.

**Comment by ditistijn** [comment]
did you fix it? i have it too
