### ISSUE TITLE
Wrong type of argument

### ISSUE THREAD

**Issue by shebet** [Sunoo/homebridge-rpi-rf-switch#6]
After installing the plugin and adding two "outlet" config using the Homebridge-x I get the following error in the logs:

[7/27/2020, 00:21:48] [Config] Homebridge restart request received
[7/27/2020, 00:21:48] [Config] UI / Bridge settings have not changed; only restarting Homebridge process
[7/27/2020, 00:21:48] [HB Supervisor] Sending SIGTERM to Homebridge
[7/27/2020, 00:21:52] [HB Supervisor] Restarting Homebridge...
[7/27/2020, 00:21:52] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/27/2020, 00:21:52] [HB Supervisor] Started Homebridge v1.1.1 with PID: 4731
[7/27/2020, 00:21:53] Loaded config.json with 0 accessories and 2 platforms.
[7/27/2020, 00:21:53] ---
[7/27/2020, 00:21:54] Loaded plugin: homebridge-config-ui-x@4.24.0
[7/27/2020, 00:21:54] Registering platform 'homebridge-config-ui-x.config'
[7/27/2020, 00:21:54] ---
[7/27/2020, 00:21:55] Loaded plugin: homebridge-rpi-rf-switch@2.2.0
[7/27/2020, 00:21:55] Registering platform 'homebridge-rpi-rf-switch.rfSwitch'
[7/27/2020, 00:21:55] ---
[7/27/2020, 00:21:55] [HB Supervisor] Sending SIGKILL to Homebridge
[7/27/2020, 00:21:55] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGKILL
[7/27/2020, 00:22:00] [HB Supervisor] Restarting Homebridge...
[7/27/2020, 00:22:00] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/27/2020, 00:22:00] [HB Supervisor] Started Homebridge v1.1.1 with PID: 4751
[7/27/2020, 00:22:01] Loaded config.json with 0 accessories and 2 platforms.
[7/27/2020, 00:22:01] ---
[7/27/2020, 00:22:02] Loaded plugin: homebridge-config-ui-x@4.24.0
[7/27/2020, 00:22:02] Registering platform 'homebridge-config-ui-x.config'
[7/27/2020, 00:22:02] ---
[7/27/2020, 00:22:02] Loaded plugin: homebridge-rpi-rf-switch@2.2.0
[7/27/2020, 00:22:02] Registering platform 'homebridge-rpi-rf-switch.rfSwitch'
[7/27/2020, 00:22:02] ---
[7/27/2020, 00:22:03] Loaded plugin: homebridge-zigbee-nt@1.0.0-rc.3
[7/27/2020, 00:22:03] Registering platform 'homebridge-zigbee-nt.ZigbeeHomebridgeNTPlatform'
[7/27/2020, 00:22:03] ---
[7/27/2020, 00:22:03] Loading 2 platforms...
[7/27/2020, 00:22:03] [Config] Initializing config platform...
[7/27/2020, 00:22:03] [Config] Running in Service Mode
[7/27/2020, 00:22:03] [RF Switch] Initializing rfSwitch platform...
**[7/27/2020, 00:22:04] Error: Wrong type of arguments
    at Interpreter.createSync (/usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python/index.js:58:24)
    at new RfSwitchPlatform (/usr/local/lib/node_modules/homebridge-rpi-rf-switch/src/index.ts:63:28)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)**
[7/27/2020, 00:22:04] Got SIGTERM, shutting down Homebridge...
[7/27/2020, 00:22:09] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

The config.json file looks correct and generated by the plugin:

**{
    "bridge": {
        "name": "Homebridge B634",
        "username": "0E:13:7C:CD:B6:34",
        "port": 51974,
        "pin": "786-99-349"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Outlet 1",
                    "on_code": 86101,
                    "off_code": 86099,
                    "pulselength": 350,
                    "protocol": 1,
                    "codelength": 24
                },
                {
                    "name": "Outlet 2",
                    "on_code": 83029,
                    "off_code": 83023,
                    "pulselength": 350,
                    "protocol": 1,
                    "codelength": 24
                }
            ],
            "name": "RF Switch",
            "gpio": 17,
            "repeat": 10,
            "platform": "rfSwitch"
        }
    ]
}**

Any idea where to look for a possible solution?
Thanks

**Comment by Sunoo** [comment]
I'm not sure I understand why that's happening for you, I took a guess and pushed a beta though, give it a shot and see if things look any different for you. You can install it with `sudo npm install -g homebridge-rpi-rf-switch@beta --unsafe-perm`.

**Comment by shebet** [comment]
I reset the Homebridge and install the beta one. Still I got this in the logs:

**[7/27/2020, 08:12:26] [HB Supervisor] Starting Homebridge with extra flags: -I
[7/27/2020, 08:12:26] [HB Supervisor] Started Homebridge v1.1.1 with PID: 15351
[7/27/2020, 08:12:27] Loaded config.json with 0 accessories and 2 platforms.
[7/27/2020, 08:12:27] ---
[7/27/2020, 08:12:28] Loaded plugin: homebridge-config-ui-x@4.24.0
[7/27/2020, 08:12:28] Registering platform 'homebridge-config-ui-x.config'
[7/27/2020, 08:12:28] ---
[7/27/2020, 08:12:29] Loaded plugin: homebridge-rpi-rf-switch@2.2.1-beta.0
[7/27/2020, 08:12:29] Registering platform 'homebridge-rpi-rf-switch.rfSwitch'
[7/27/2020, 08:12:29] ---
[7/27/2020, 08:12:29] Loading 2 platforms...
[7/27/2020, 08:12:29] [Config] Initializing config platform...
[7/27/2020, 08:12:29] [Config] Running in Service Mode
[7/27/2020, 08:12:29] [RF Switch] Initializing rfSwitch platform...
[7/27/2020, 08:12:29] Error: Wrong type of arguments
    at Interpreter.createSync (/usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python/index.js:58:24)
    at new RfSwitchPlatform (/usr/local/lib/node_modules/homebridge-rpi-rf-switch/src/index.ts:63:28)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[7/27/2020, 08:12:29] Got SIGTERM, shutting down Homebridge...**

Is there any other log or input I can provide that might help you?

**Comment by Sunoo** [comment]
Hmm... something must be different on your setup then mine. I’m going to keep trying to recreate your issue though. Can you tell me what version of Node you have on your device?

**Comment by Sunoo** [comment]
Okay, I think I found it. You probably don't have rpi-rf installed on your system. You can do that with `sudo pip3 install rpi-rf` as mentioned in the [installation instructions](https://github.com/Sunoo/homebridge-rpi-rf-switch#installation) for this project.

**Comment by shebet** [comment]
I feel so dumb not noticing this. My assumption has been that using Homebridge-ui-x will take care of this dependencies. Also the plugin is named **"homebridge-rpi-rf-switch"** so I though this is the rf-rpi plugin but of course I should have paid more attention.
Now it works like a charm.

Thanks :)

**Comment by Sunoo** [comment]
@shebet Great, glad we figured it out. I'll be adding a clearer error message, and also a postinstall script to attempt to automatically install rpi-rf soon to try to avoid this in the future.
